---
version: "3.8"

volumes:
  pgadmin-data:
  postgres-data:

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    user: 1000:1000
    env_file:
      - app/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "9201:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

      # Prevent use of sudo or use external mail server
      PGADMIN_DISABLE_POSTFIX: "true"

      # To allow running in desktop mode (SERVER_MODE = False), a runtime
      # application is provided to host and display the pgAdmin code (sometimes
      # referred to as the application server). In this mode, each user runs
      # their own instance of pgAdmin, thus no authentication or user management
      # is required. https://www.pgadmin.org/faq/#2
      PGADMIN_CONFIG_SERVER_MODE: "False"
    env_file:
      - app/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  fastapi:
    image: fastapitest:latest
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres