"""Alembic Autogenerate add phone_number col for users table

Revision ID: dbcc68c2ea8c
Revises: a6cf73d06055
Create Date: 2022-04-17 19:49:07.528743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dbcc68c2ea8c"
down_revision = "a6cf73d06055"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
